services:
  web:
    container_name: web_container
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

networks:
  app_network:
    driver: bridge
