version: "3.8"

services:
  db:
    image: postgres:16
    container_name: db_container
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
  web:
    container_name: web_container
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

volumes:
  pgdata:

networks:
  app_network:
    driver: bridge
