packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@next/bundle-analyzer": ^15.2.3
  "@types/node": ^22.13.10
  "@yopem-ui/react-icons": ^0.0.5
  "dotenv-cli": ^8.0.0
  next: ^15.2.3
  react-hook-form: "7.56.2"
  superjson: ^2.2.2
  zod: ^3.24.2

catalogs:
  react:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
  tailwindcss:
    "@tailwindcss/postcss": ^4.0.14
    "tailwindcss": "^4.0.9"
    "tailwindcss-animate": "^1.0.7"
    "tw-animate-css": "^1.2.4"
  tooling:
    "@yopem/eslint-config": ^0.1.8
    "@yopem/prettier-config": ^0.1.1
    "@yopem/typescript-config": ^0.1.0
    eslint: ^9.21.0
    prettier: ^3.5.3
    tailwindcss: ^4.0.2
    typescript: ^5.7.3
  trpc:
    "@trpc/client": ^11.1.0
    "@trpc/server": ^11.1.0
    "@trpc/react-query": ^11.1.0
    "@trpc/tanstack-react-query": ^11.1.0
