packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@t3-oss/env-nextjs": ^0.12.0
  "@types/node": ^22.13.10
  "dotenv-cli": ^8.0.0
  next: ^15.2.3
  zod: ^3.24.2

catalogs:
  tailwindcss:
    "@tailwindcss/postcss": ^4.0.14
    "tailwindcss": "^4.0.9"
    "tailwindcss-animate": "^1.0.7"
  react:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.10
    "@types/react-dom": ^19.0.4
  tooling:
    "@yopem/eslint-config": ^0.1.8
    "@yopem/prettier-config": ^0.1.1
    "@yopem/typescript-config": ^0.1.0
    eslint: ^9.21.0
    prettier: ^3.5.3
    tailwindcss: ^4.0.2
    typescript: ^5.7.3
