#:schema node_modules/wrangler/config-schema.json

name = "tokodaim"
compatibility_date = "2024-05-02"
pages_build_output_dir = "./dist"


[[d1_databases]]
binding = "DB"
database_name = "tokodaim"
database_id = "04d45bd5-b59b-4937-869b-b2e7b9ad2ac0"
migrations_dir = "./src/lib/db/migrations"


[vars]
APP_ENV="production"
PUBLIC_DOMAIN="tokodaim.com"
PUBLIC_SITE_TITLE="Tokodaim"
PUBLIC_SITE_DESCRIPTION="Tokodaim desc"
PUBLIC_FACEBOOK_USERNAME="tokodaim"
PUBLIC_TWITTER_USERNAME="tokodaim"
PUBLIC_INSTAGRAM_USERNAME="tokodaim"
PUBLIC_YOUTUBE_USERNAME="@tokodaim"
PUBLIC_SUPPORT_EMAIL="support@tokodaim.com"
PUBLIC_WHATSAPP_NUMBER="6283822727338"
PUBLIC_ADDRESS="Jl. Bakti Pemuda, Drien Rampak, Johan Pahlawan, Kabupaten Aceh Barat, Aceh 23611"
PUBLIC_LOGO_URL="https://media.teknodaim.com/wp-content/uploads/2021/07/Teknodaim-Text-Logo-V3.png.webp"
PUBLIC_LOGO_OG_URL="https://media.teknodaim.com/wp-content/uploads/2019/06/Teknodaim-Wall-min.png"
PUBLIC_LOGO_OG_WIDTH="800px"
PUBLIC_LOGO_OG_HEIGHT="450px"
GOOGLE_CLIENT_ID="174500547602-dt0su8k1325dqbbuto0mbs2d6n5t35bi.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET="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"
GOOGLE_REDIRECT_URL="http://localhost:8788/auth/login/google/callback"
R2_BUCKET="tokodaim"
R2_REGION="auto"
R2_ACCOUNT_ID="6e7987b6d5b2c28790eb8d863cd23aba"
R2_ACCESS_KEY="dd8179b32540f1d773997ad35732c394"
R2_SECRET_KEY="4a6f8a6a52a017099cf29dcb0eabf1f864e80f5c4c224f8d4924f36ca7678ccc"
R2_DOMAIN="assets.tokodaim.com"
DIGIFLAZZ_USERNAME="weponig14JZW"
DIGIFLAZZ_API_KEY_DEV="dev-15887b10-bc31-11ed-be43-897c133ef6c3"
DIGIFLAZZ_API_KEY_PROD="a500fb70-feca-54c6-8c4b-0cc41e348e16"
DIGIFLAZZ_WEBHOOK_ID="Dz4eng"
DIGIFLAZZ_WEBHOOK_SECRET="superRahasia"
TRIPAY_API_KEY_DEV="DEV-rrqfcDk6AUYbUU3Njrgix7068TW1KZb7QC4gFRKK"
TRIPAY_PRIVATE_KEY_DEV="JqXhw-MqYBm-CM0xK-CFzP2-quh3o"
TRIPAY_API_KEY_PROD="LXHJzj88riX67rzSrOs3d1QPXREbqjd5rmL3ntMf"
TRIPAY_PRIVATE_KEY_PROD="9NP6T-OLKVU-3te9r-movl8-iir07"
TRIPAY_MERCHANT_CODE_DEV="T20278"
TRIPAY_MERCHANT_CODE_PROD="T20278"
